[build]
  command = "cd src/nuxtjs && yarn install && yarn build && yarn start"
  publish = "src/nuxtjs/.nuxt/dist"

[template.environment]
  LIFF_ID = "Your LIFF ID which is aquired from LINE Dev Center"
